### ISSUE TITLE
Client SSH tunnel integration

### ISSUE THREAD

**Issue by willscott** [UWNetworksLab/colony#5]
Tracking bug for allowing the client app to use a provisioned server
- [ ] Working SSH Tunnel VPN
- [ ] Exposing SSH Tunnel as a cordova API

**Comment by ryscheng** [comment]
This seems like a less likely-option now.

Connectbot allows you to setup a local SOCKS5 proxy, but cannot configure apps to use it
http://www.devineloper.com/2013/08/28/setup-socks-proxy-android-without-root/
https://github.com/connectbot/connectbot/

sshtunnel can do the same, and with a rooted phone, use redsocks to setup iptables rules to route all traffic over the tunnel.
https://code.google.com/p/sshtunnel/
http://darkk.net.ru/redsocks/

To continue the SSH-line of thought, we'd need to write a VPN->SSH plugin.
I think it'd be easier to provision the server with L2TP/IPSec and just configure the client's built-in VPN client to use it.
Deferring to this issue:
https://github.com/uProxy/colony/issues/8

**Comment by ryscheng** [comment]
Moving discussion to 
https://github.com/uProxy/colony/issues/8
